version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:8.0
    container_name: library
    # This will run the container on startup
    # restart: always
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - "./.mysql/db:/var/lib/mysql"
